### ISSUE TITLE
tracker.trackerfix.com outside OpenVPN

### ISSUE THREAD

**Issue by Verguldebarman** [haugene/docker-transmission-openvpn#1709]
**Before creating this issue I have:**

- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X] Tried to add as much relevant information to the issue as possible

**Describe the problem**

Everything works flawless and perfect. I really like your work !!!  

One thing tho; it looks like (DNS) requests to 

1. tracker.trackerfix.com
2. 9.rarbg.me
3. 9.rarbg.to
4. portcheck.transmissionbt.com

are done outside OpenVPN tunnel. (Same as "google.com" requests, but those are okay as container healthcheck uses this. )

As these (DNS) requests run outside OpenVPN, it exposes me..... 

See below extract from my pi-hole set-up, what checks all DNS requests. IP 192.168.0.119 is the address of the system where I run docker-transmission-openvpn.

```

Time | Type | Domain | Client | Status | Reply | Action
-- | -- | -- | -- | -- | -- | --

2021-02-09 17:46:50 | AAAA | tracker.trackerfix.com | 192.168.0.119 | OK (cached) | NODATA (1.3ms) | Blacklist
2021-02-09 17:46:50 | A | tracker.trackerfix.com | 192.168.0.119 | OK (cached) | IP (1.4ms) | Blacklist
2021-02-09 17:46:44 | AAAA | google.com | 192.168.0.119 | OK (cached) | IP (0.8ms) | Blacklist
2021-02-09 17:46:44 | A | google.com | 192.168.0.119 | OK (forwarded to one.one.one.one#53)INSECURE | IP (18.6ms) | Blacklist
2021-02-09 17:46:23 | A | 9.rarbg.me | 192.168.0.119 | OK (cached) | IP (1.4ms) | Blacklist
```

I have checked working of OpenVPN via bash command line in the container and the vpn tunnel is actively used.

**Add your docker run command or docker-compose file**

 
 ```
n/a
 ```

**Logs**

 ```
above

 ```

**Host system:**

 ```
LibreElec 8.2.5 (kernel: Linux 3.14.29)
Docker 1.13.1 (sorry... really old, but I cannot use any higher version on my setup)
Checked the same on RPi4 with Ubuntu 20.4.2 TLS and docker 20.10.3 

Both are connected to a Synology NAS for data stored via NFS

 ```

**Comment by pkishino** [comment]
can you check which dns is set in your resolv.conf file ?

**Comment by Verguldebarman** [comment]
Yeah, my router's IP ...  :-) 

Changed it to my two pi-hole machines and will let you know if I still see DNS queries popping up!
Thanks!!
