### ISSUE TITLE
PIA - "Tracker gave HTTP response code 0 (No Response)" when trying to use a udp based private tracker

### ISSUE THREAD

**Issue by MrJamesT** [haugene/docker-transmission-openvpn#1944]
### Is there a pinned issue for this?

- [X] I have read the pinned issues

### Is there an existing or similar issue for this?

- [X] I have searched the existing issues

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [ ] I have tried using dev branch

### Config used

transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/net:/dev/net:z
      - /volume1/video/downloads:/data
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=austria,romania,czech_republic
      - OPENVPN_USERNAME=***
      - 'OPENVPN_PASSWORD=***
      - 'OPENVPN_OPTS=--mute-replay-warnings'
      - LOCAL_NETWORK=192.168.0.0/24
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    dns:
      - 1.1.1.1
      - 1.0.0.1

### Current Behavior

Package works flawlessly with my 3 public trackers but when I try to add a torrent from a udp based private tracker, it doesn't start downloading/seeding.
When I looked into the log files, I found this line to be the cause of the issue:
`Tracker gave HTTP response code 0 (No Response) (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)`
I tried checking `Enable uTP for peer communication` but it didn't help. I tested the tracker on my pc with qbitorrent and it works just fine.

### Expected Behavior

Would work even with a private udp based tracker.

### How have you tried to solve the problem?

1. Restarted the docker container
2. Restarted my NAS
3. Changed the DNS servers from PIA to Cloudflare

### Log output

These are the logs after restart, there's something interesting about UDP not working maybe?
`[2021-09-02 14:36:28.466] Transmission 3.00 (bb6b5a062e) started (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/session.c:769)
[2021-09-02 14:36:28.467] RPC Server Adding address to whitelist: 127.0.0.1 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956)
[2021-09-02 14:36:28.467] RPC Server Adding address to whitelist: ::1 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956)
[2021-09-02 14:36:28.467] RPC Server Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:1243)
[2021-09-02 14:36:28.467] Port Forwarding Stopped (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/port-forwarding.c:196)
[2021-09-02 14:36:28.467] UDP Failed to set receive buffer: requested 4194304, got 425984 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:97)
[2021-09-02 14:36:28.467] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:99)
[2021-09-02 14:36:28.467] UDP Failed to set send buffer: requested 1048576, got 425984 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:105)
[2021-09-02 14:36:28.467] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:107)`

I've attached one line from the logs in the current behavior part, I've read the other logs thoroughly and they don't appear to contain anything important.

### Environment

```markdown
- OS: Synology DSM 7.0
- Docker: 20.10.3
- VPN Provider: PrivateInternetAccess
```
