### ISSUE TITLE
could not connect to tracker HTTP

### ISSUE THREAD

**Issue by spupuz** [haugene/docker-transmission-openvpn#2288]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        #sysctls:
        #    - 'net.ipv6.conf.all.disable_ipv6=1'
        volumes:
            - /zfsfiles/DockerConfig/Transmission-Openvpn/config:/config
            - /zfsfiles/Downloads:/downloads
            - /zfsfiles/Downloads/watch:/watch
            - /zfsfiles/DockerConfig/Transmission-Openvpn/openvpn:/etc/openvpn/custom/
            - /zfsfiles/DockerConfig/Transmission-Openvpn/webui:/webui
        environment:
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=nl-free-08.protonvpn.net.udp
            - OPENVPN_USERNAME=xxxxxxxxxxxxxxxxxxx
            - OPENVPN_PASSWORD=xxxxxxxxxxxxxxxxxxx
            - LOCAL_NETWORK=192.168.1.0/24
            - OVERRIDE_DNS_1=8.8.8.8
            - OVERRIDE_DNS_2=8.8.4.4
            - PEER_DNS=false
            - TRANSMISSION_RPC_USERNAME=xxxxxxxxxxxxxxxxxxx
            - TRANSMISSION_RPC_PASSWORD=xxxxxxxxxxxxxxxxxxx
            - TRANSMISSION_WATCH_DIR=/downloads/watch
            - TRANSMISSION_DOWNLOAD_DIR=/downloads/complete
            - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
            - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
            - TRANSMISSION_WATCH_DIR_ENABLED=true
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_WEB_HOME=/webui
            #- TRANSMISSION_WEB_UI=combustion
            - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
            - TRANSMISSION_DHT_ENABLED=true
            - TRANSMISSION_PEX_ENABLED=true
            - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=50
            - TRANSMISSION_RATIO_LIMIT_ENABLED=true
            - TRANSMISSION_RATIO_LIMIT=1
            - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
            - TRANSMISSION_SPEED_LIMIT_UP=4000
            - PUID=1000
            - PGID=1000
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9092:9091
        image: haugene/transmission-openvpn:dev
        restart: unless-stopped

### Current Behavior

if i do user DNS override it works but slowly and it can connect to tracker udp and https if not using DNS override it can connect only with tracker http, i'm using ProtonVPN free

### Expected Behavior

be able to connect to all type of tracker.
With transmission without vpn don't have problematics

### How have you tried to solve the problem?

i tried most of the suggested solution

### Log output

```
[2022-06-30 17:35:45.000] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Retrying announce in 347 seconds. (announcer.c:1005)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Could not connect to tracker (announcer.c:996)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Retrying announce in 20 seconds. (announcer.c:1005)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Could not connect to tracker (announcer.c:996)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Retrying announce in 20 seconds. (announcer.c:1005)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Could not connect to tracker (announcer.c:996)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Retrying announce in 20 seconds. (announcer.c:1005)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Could not connect to tracker (announcer.c:996)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Retrying announce in 310 seconds. (announcer.c:1005)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Could not connect to tracker (announcer.c:996)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Retrying announce in 311 seconds. (announcer.c:1005)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Tracker gave HTTP response code 0 (No Response) (announcer.c:996)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Retrying announce in 346 seconds. (announcer.c:1005)
[2022-06-30 17:35:46.967] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Tracker gave HTTP response code 307 (Temporary Redirect) (announcer.c:996)
[2022-06-30 17:35:46.967] Rxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Retrying announce in 339 seconds. (announcer.c:1005)
[2022-06-30 17:35:48.088] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx IPv4 DHT announce done (tr-dht.c:545)
[2022-06-30 17:35:49.083] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Could not connect to tracker (announcer.c:996)
[2022-06-30 17:35:49.083] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Retrying announce in 342 seconds. (announcer.c:1005)

```

### HW/SW Environment

```markdown
- OS: OMV 6.0 Debian
- Docker: dev branch
```

**Comment by UnconditionalLoop** [comment]
Why 

ports:
- 9092:9091

**Comment by pkishino** [comment]
Please try this with vpn turned on outside of the docker and use transmission client.. I suspect this is vpn related and not container. I use a different provider and do not see these problems..
